rtabmap_viz:
  ros__parameters:
    subscribe_rgbd: true
    subscribe_scan: false
    subscribe_odom: true
    approx_sync: true
    topic_queue_size: 10
    sync_queue_size: 10

    frame_id: "base_link"
    map_frame_id: "map"
    odom_frame_id: "odom"

    # ← viz도 자기 구독 QoS를 BestEffort로
    qos_image: 2
    qos_camera_info: 2
    qos_scan: 2
    qos_odom: 2
    qos_user_data: 2
